// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'adapters/ffi/http/models.dart';
import 'adapters/ffi/service_exporter_ffi_adapter.dart';
import 'adapters/ffi/service_ffi_adapter.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.10.0';

  @override
  int get rustContentHash => -79516352;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'strawberry_background',
        ioDirectory: '../target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ServiceFfiAdapter>
  crateAdaptersFfiServiceExporterFfiAdapterServiceExporterFfiAdapterRuntimeFfiAdapter({
    required ServiceExporterFfiAdapter that,
  });

  Future<FfiHttpResponse>
  crateAdaptersFfiServiceFfiAdapterServiceFfiAdapterExecuteHttpEndpoint({
    required ServiceFfiAdapter that,
    required FfiHttpEndpoint ffiEndpoint,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ServiceExporterFfiAdapter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ServiceExporterFfiAdapter;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ServiceExporterFfiAdapterPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ServiceFfiAdapter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ServiceFfiAdapter;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ServiceFfiAdapterPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ServiceFfiAdapter>
  crateAdaptersFfiServiceExporterFfiAdapterServiceExporterFfiAdapterRuntimeFfiAdapter({
    required ServiceExporterFfiAdapter that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateAdaptersFfiServiceExporterFfiAdapterServiceExporterFfiAdapterRuntimeFfiAdapterConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateAdaptersFfiServiceExporterFfiAdapterServiceExporterFfiAdapterRuntimeFfiAdapterConstMeta =>
      const TaskConstMeta(
        debugName: "ServiceExporterFfiAdapter_runtime_ffi_adapter",
        argNames: ["that"],
      );

  @override
  Future<FfiHttpResponse>
  crateAdaptersFfiServiceFfiAdapterServiceFfiAdapterExecuteHttpEndpoint({
    required ServiceFfiAdapter that,
    required FfiHttpEndpoint ffiEndpoint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
            that,
            serializer,
          );
          sse_encode_box_autoadd_ffi_http_endpoint(ffiEndpoint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_http_response,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateAdaptersFfiServiceFfiAdapterServiceFfiAdapterExecuteHttpEndpointConstMeta,
        argValues: [that, ffiEndpoint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateAdaptersFfiServiceFfiAdapterServiceFfiAdapterExecuteHttpEndpointConstMeta =>
      const TaskConstMeta(
        debugName: "ServiceFfiAdapter_execute_http_endpoint",
        argNames: ["that", "ffiEndpoint"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ServiceExporterFfiAdapter =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ServiceExporterFfiAdapter =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ServiceFfiAdapter =>
      wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ServiceFfiAdapter =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter;

  @protected
  ServiceExporterFfiAdapter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ServiceExporterFfiAdapterImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ServiceFfiAdapter
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ServiceFfiAdapterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ServiceExporterFfiAdapter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ServiceExporterFfiAdapterImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ServiceFfiAdapter
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ServiceFfiAdapterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ServiceExporterFfiAdapter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ServiceExporterFfiAdapterImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  ServiceFfiAdapter
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ServiceFfiAdapterImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiHttpEndpoint dco_decode_box_autoadd_ffi_http_endpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_http_endpoint(raw);
  }

  @protected
  FfiHttpEndpoint dco_decode_ffi_http_endpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return FfiHttpEndpoint(
      path: dco_decode_String(arr[0]),
      domain: dco_decode_String(arr[1]),
      body: dco_decode_opt_list_prim_u_8_strict(arr[2]),
      timeoutMillis: dco_decode_u_64(arr[3]),
      headers: dco_decode_opt_list_record_string_string(arr[4]),
      pathParams: dco_decode_opt_list_record_string_string(arr[5]),
      queryParams: dco_decode_opt_list_record_string_string(arr[6]),
      method: dco_decode_String(arr[7]),
      requiresEncryption: dco_decode_bool(arr[8]),
      requiresDecryption: dco_decode_bool(arr[9]),
      userAgent: dco_decode_opt_String(arr[10]),
      contentType: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  FfiHttpResponse dco_decode_ffi_http_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiHttpResponse(
      status: dco_decode_u_16(arr[0]),
      headers: dco_decode_list_record_string_string(arr[1]),
      body: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  List<(String, String)>? dco_decode_opt_list_record_string_string(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_record_string_string(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ServiceExporterFfiAdapter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ServiceExporterFfiAdapterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ServiceFfiAdapter
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ServiceFfiAdapterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ServiceExporterFfiAdapter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ServiceExporterFfiAdapterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ServiceFfiAdapter
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ServiceFfiAdapterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ServiceExporterFfiAdapter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ServiceExporterFfiAdapterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ServiceFfiAdapter
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ServiceFfiAdapterImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiHttpEndpoint sse_decode_box_autoadd_ffi_http_endpoint(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_http_endpoint(deserializer));
  }

  @protected
  FfiHttpEndpoint sse_decode_ffi_http_endpoint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_domain = sse_decode_String(deserializer);
    var var_body = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_timeoutMillis = sse_decode_u_64(deserializer);
    var var_headers = sse_decode_opt_list_record_string_string(deserializer);
    var var_pathParams = sse_decode_opt_list_record_string_string(deserializer);
    var var_queryParams = sse_decode_opt_list_record_string_string(
      deserializer,
    );
    var var_method = sse_decode_String(deserializer);
    var var_requiresEncryption = sse_decode_bool(deserializer);
    var var_requiresDecryption = sse_decode_bool(deserializer);
    var var_userAgent = sse_decode_opt_String(deserializer);
    var var_contentType = sse_decode_opt_String(deserializer);
    return FfiHttpEndpoint(
      path: var_path,
      domain: var_domain,
      body: var_body,
      timeoutMillis: var_timeoutMillis,
      headers: var_headers,
      pathParams: var_pathParams,
      queryParams: var_queryParams,
      method: var_method,
      requiresEncryption: var_requiresEncryption,
      requiresDecryption: var_requiresDecryption,
      userAgent: var_userAgent,
      contentType: var_contentType,
    );
  }

  @protected
  FfiHttpResponse sse_decode_ffi_http_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_u_16(deserializer);
    var var_headers = sse_decode_list_record_string_string(deserializer);
    var var_body = sse_decode_list_prim_u_8_strict(deserializer);
    return FfiHttpResponse(
      status: var_status,
      headers: var_headers,
      body: var_body,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<(String, String)>? sse_decode_opt_list_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_record_string_string(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    ServiceExporterFfiAdapter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ServiceExporterFfiAdapterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    ServiceFfiAdapter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ServiceFfiAdapterImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    ServiceExporterFfiAdapter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ServiceExporterFfiAdapterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    ServiceFfiAdapter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ServiceFfiAdapterImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceExporterFfiAdapter(
    ServiceExporterFfiAdapter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ServiceExporterFfiAdapterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerServiceFfiAdapter(
    ServiceFfiAdapter self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ServiceFfiAdapterImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ffi_http_endpoint(
    FfiHttpEndpoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_http_endpoint(self, serializer);
  }

  @protected
  void sse_encode_ffi_http_endpoint(
    FfiHttpEndpoint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.domain, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.body, serializer);
    sse_encode_u_64(self.timeoutMillis, serializer);
    sse_encode_opt_list_record_string_string(self.headers, serializer);
    sse_encode_opt_list_record_string_string(self.pathParams, serializer);
    sse_encode_opt_list_record_string_string(self.queryParams, serializer);
    sse_encode_String(self.method, serializer);
    sse_encode_bool(self.requiresEncryption, serializer);
    sse_encode_bool(self.requiresDecryption, serializer);
    sse_encode_opt_String(self.userAgent, serializer);
    sse_encode_opt_String(self.contentType, serializer);
  }

  @protected
  void sse_encode_ffi_http_response(
    FfiHttpResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.status, serializer);
    sse_encode_list_record_string_string(self.headers, serializer);
    sse_encode_list_prim_u_8_strict(self.body, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_record_string_string(
    List<(String, String)>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_record_string_string(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ServiceExporterFfiAdapterImpl extends RustOpaque
    implements ServiceExporterFfiAdapter {
  // Not to be used by end users
  ServiceExporterFfiAdapterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ServiceExporterFfiAdapterImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib
            .instance
            .api
            .rust_arc_increment_strong_count_ServiceExporterFfiAdapter,
    rustArcDecrementStrongCount:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_ServiceExporterFfiAdapter,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_ServiceExporterFfiAdapterPtr,
  );

  Future<ServiceFfiAdapter> runtimeFfiAdapter() => RustLib.instance.api
      .crateAdaptersFfiServiceExporterFfiAdapterServiceExporterFfiAdapterRuntimeFfiAdapter(
        that: this,
      );
}

@sealed
class ServiceFfiAdapterImpl extends RustOpaque implements ServiceFfiAdapter {
  // Not to be used by end users
  ServiceFfiAdapterImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ServiceFfiAdapterImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ServiceFfiAdapter,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ServiceFfiAdapter,
    rustArcDecrementStrongCountPtr:
        RustLib
            .instance
            .api
            .rust_arc_decrement_strong_count_ServiceFfiAdapterPtr,
  );

  Future<FfiHttpResponse> executeHttpEndpoint({
    required FfiHttpEndpoint ffiEndpoint,
  }) => RustLib.instance.api
      .crateAdaptersFfiServiceFfiAdapterServiceFfiAdapterExecuteHttpEndpoint(
        that: this,
        ffiEndpoint: ffiEndpoint,
      );
}
