// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from`, `to_domain_endpoint`

class FfiHttpEndpoint {
  final String path;
  final String domain;
  final Uint8List? body;
  final BigInt timeoutMillis;
  final List<(String, String)>? headers;
  final List<(String, String)>? pathParams;
  final List<(String, String)>? queryParams;
  final String method;
  final bool requiresEncryption;
  final bool requiresDecryption;
  final String? userAgent;
  final String? contentType;

  const FfiHttpEndpoint({
    required this.path,
    required this.domain,
    this.body,
    required this.timeoutMillis,
    this.headers,
    this.pathParams,
    this.queryParams,
    required this.method,
    required this.requiresEncryption,
    required this.requiresDecryption,
    this.userAgent,
    this.contentType,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      domain.hashCode ^
      body.hashCode ^
      timeoutMillis.hashCode ^
      headers.hashCode ^
      pathParams.hashCode ^
      queryParams.hashCode ^
      method.hashCode ^
      requiresEncryption.hashCode ^
      requiresDecryption.hashCode ^
      userAgent.hashCode ^
      contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiHttpEndpoint &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          domain == other.domain &&
          body == other.body &&
          timeoutMillis == other.timeoutMillis &&
          headers == other.headers &&
          pathParams == other.pathParams &&
          queryParams == other.queryParams &&
          method == other.method &&
          requiresEncryption == other.requiresEncryption &&
          requiresDecryption == other.requiresDecryption &&
          userAgent == other.userAgent &&
          contentType == other.contentType;
}

class FfiHttpResponse {
  final int status;
  final List<(String, String)> headers;
  final Uint8List body;

  const FfiHttpResponse({
    required this.status,
    required this.headers,
    required this.body,
  });

  @override
  int get hashCode => status.hashCode ^ headers.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiHttpResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          headers == other.headers &&
          body == other.body;
}
