// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'service_ffi_adapter.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `create_service_exporter_ffi_adapter`, `new`, `runtime`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ServiceExporterFfiAdapter>>
abstract class ServiceExporterFfiAdapter implements RustOpaqueInterface {
  Future<ServiceFfiAdapter> runtimeFfiAdapter();
}
