// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'http/models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ServiceFfiAdapter>>
abstract class ServiceFfiAdapter implements RustOpaqueInterface {
  Future<FfiHttpResponse> executeHttpEndpoint({
    required FfiHttpEndpoint ffiEndpoint,
  });
}
